language: go

go:
  - 1.4
  - 1.5
  - tip

before_script:
  - make

sudo: false

script: make test

notifications:
  email: false

branches:
  only:
    - master
    - development

matrix:
  allow_failures:
    - go: tip