adapter:
  protocol: smtp # smtp or lmtp
  host: 127.0.0.1
  port: 2525
  hostname: localhost
  auth: true
  tls: false
  ssl_hostname: localhost
  ssl_pub_key: examples/test.pem
  ssl_prv_key: examples/test.key
  welcome_msg: Falcon Mail Server
  max_mail_size: 5242880
  rate_limit: 2
  workers_size: 20

storage:
  adapter: postgresql
  host: localhost
  port: 5432
  username: leo
  password:
  database: falcon_dev
  pool: 20
  pool_idle: 5

  auth_sql: "SELECT id, password FROM inboxes WHERE username = $1" # $1 - username, should return id and password

  settings_sql: "SELECT max_size, rate_limit FROM inboxes WHERE id = $1" # $1 - inbox_id

  messages_sql: "INSERT INTO messages(inbox_id, subject, sent_at, from_email, from_name, to_email, to_name, html_body, text_body, raw_body, email_size, created_at, updated_at) VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW(), NOW()) RETURNING id" # returning id is MUST
  attachments_sql: "INSERT INTO attachments(inbox_id, message_id, filename, attachment_type, content_type, content_id, transfer_encoding, attachment_body, attachment_size, created_at, updated_at) VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW()) RETURNING id"

  max_messages_enabled: true
  max_messages_cleanup_sql: "DELETE FROM messages WHERE inbox_id = $1 AND (SELECT COUNT(*) FROM messages WHERE inbox_id = $1) >= $2 AND id IN (SELECT id FROM messages WHERE inbox_id = $1 ORDER BY id DESC LIMIT 3 OFFSET $2) RETURNING id" # $1 - inbox_id, $2 - max messages
  max_attachments_cleanup_sql: "DELETE FROM attachments WHERE inbox_id = $1 AND message_id = $2 RETURNING id" # $1 - inbox_id, $2 - message id
  # spamassassin sql if spamassassin is enabled
  spamassassin_sql: "UPDATE messages SET spam_report=$3 WHERE inbox_id = $1 AND id = $2 RETURNING id"
  # clamav sql if clamav is enabled
  clamav_sql: "UPDATE messages SET viruses_report=$3 WHERE inbox_id = $1 AND id = $2 RETURNING id"
  # pop3 sql if enabled
  pop3_count_and_size_messages: "SELECT count(id), COALESCE(SUM(email_size), 0) FROM messages WHERE id IN (SELECT id FROM messages WHERE inbox_id = $1 ORDER BY id DESC LIMIT 50)"
  pop3_messages_list: "SELECT id, email_size FROM messages WHERE inbox_id = $1 ORDER BY id DESC LIMIT 50"
  pop3_message_one: "SELECT email_size, raw_body FROM messages WHERE inbox_id = $1 AND id = $2"
  pop3_message_delete: "DELETE FROM messages WHERE inbox_id = $1 AND id = $2 RETURNING id"
  # email address mode sql if enabled
  email_address_mode_sql: "SELECT id FROM inboxes WHERE email_username = $1 and email_username_enabled = 't'"

email_address_mode:
  enabled: false
  domains:
    - "example.com"
    - "localhost"

pop3:
  enabled: true
  host: 127.0.0.1
  port: 1110
  hostname: localhost
  tls: false
  ssl_hostname: localhost
  ssl_pub_key: examples/test.pem
  ssl_prv_key: examples/test.key

spamassassin:
  enabled: false
  ip: 127.0.0.1 # it work only by tcp ip socket
  port: 783
  timeout: 30

clamav:
  enabled: false
  host: 127.0.0.1
  port: 3310
  timeout: 30

redis:
  enabled: true
  host: 127.0.0.1
  port: 6379
  pool: 20
  timeout: 5
  namespace: development
  hook_username: adminadmin
  hook_password: monkey
  sidekiq_queue: server
  sidekiq_class: SmtpServerJob

proxy:
  enabled: true
  proxy_mode: true
  host: localhost
  port: 2526
  client_ports:
    smtp: []
    pop3: []
