adapter:
  protocol: smtp # smtp or lmtp
  host: 127.0.0.1
  port: 1025
  auth: true
  tls: false
  ssl_hostname: localhost
  ssl_pub_key: examples/test.pem
  ssl_prv_key: examples/test.key
  welcome_msg: Falcon Mail Server
  max_mail_size: 10240000
  allow_hosts: 127.0.0.1

storage:
  adapter: postgresql
  host: localhost
  port: 5432
  username: leo
  password:
  database: go-falcon
  pool: 5
  mailbox_sql: "SELECT id, raw_password FROM mailboxes WHERE email = $1" # $1 - email, should return ID and raw password
  messages_sql: "INSERT INTO messages(mailbox_id, subject, sent_at, from_email, from_name, to_email, to_name, html_body, text_body, raw_email) VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id" # returning id is MUST

proxy:
  enabled: true
  host: localhost
  port: 2526