adapter:
  protocol: smtp # smtp or lmtp
  host: 127.0.0.1
  port: 1025
  auth: true
  tls: false
  ssl_hostname: localhost
  ssl_pub_key: examples/test.pem
  ssl_prv_key: examples/test.key
  welcome_msg: Falcon Mail Server
  max_mail_size: 5242880
  allow_hosts: 127.0.0.1

storage:
  adapter: postgresql
  host: localhost
  port: 5432
  username: leo
  password:
  database: go-falcon
  pool: 5

  max_messages_field: true
  max_messages_sql: "SELECT count(*) FROM messages WHERE mailbox_id = $1"
  max_messages_cleanup_sql: "DELETE FROM messages WHERE mailbox_id = $1 AND id IN (SELECT id FROM messages WHERE mailbox_id = $1 ORDER BY id LIMIT $2) RETURNING id"
  max_attachments_cleanup_sql: "DELETE FROM attachments WHERE mailbox_id = $1 AND message_id IN ($2) RETURNING id"

  auth_sql: "SELECT id, raw_password, max_emails FROM mailboxes WHERE email = $1" # $1 - mailbox_id
  messages_sql: "INSERT INTO messages_[[mailbox_id]](mailbox_id, subject, sent_at, from_email, from_name, to_email, to_name, html_body, text_body, raw_email) VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id" # returning id is MUST
  attachments_sql: "INSERT INTO attachments_[[mailbox_id]](mailbox_id, message_id, filename, attachment_type, content_type, content_id, transfer_encoding, body) VALUES($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id"

proxy:
  enabled: true
  host: localhost
  port: 2526
