adapter:
  protocol: smtp # smtp or lmtp
  host: 127.0.0.1
  port: 25
  workers_number: 3
  allow_hosts: 127.0.0.1

storage:
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: password
  database: go-falcon

proxy:
  enabled: false
  host: localhost
  port: 2525