smtp:
  enabled: true
  host: 127.0.0.1
  port: 25

lmtp:
  enabled: true
  host: 127.0.0.1
  port: 2525

storage:
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: password